name: Electron Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Electron Builder
        uses: paneron/action-electron-builder@v1.8.1
        with:
          skip_package_manager_install: false
          package_manager: npm
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mac_certs: BASE64_ENCODED_CERTIFICATE_FOR_MACOS
          mac_certs_password: CERTIFICATE_PASSWORD
          release: true
          windows_certs: BASE64_ENCODED_CERTIFICATE_FOR_WINDOWS
          windows_certs_password: CERTIFICATE_PASSWORD
          package_root: .
          build_script_name: build
          skip_build: false
          use_vue_cli: false
          args: '--some-arg=value'
          max_attempts: 3
          app_root: 'path/to/app'
